import {model, Model, Schema, HydratedDocument} from 'mongoose';
import {IMtgCard} from '../interfaces/MtgCard';

type ModelType = Model<IMtgCard, Record<string, never>>;

const schema = new Schema<IMtgCard, ModelType>(
	{
		object: {type: String, index: true, required: true},
		id: {type: String, index: true, required: true},
		oracle_id: {type: String, default: null},		
		multiverse_ids: [{type: Number}],
        mtgo_id: {type: Number},
        mtgo_foil_id: {type: Number},
        tcgplayer_id: {type: Number},
        cardmarket_id: {type: Number},
        name: {type: String, index: true, required: true},
        lang: {type: String, required: true},
        released_at: {type: String},
        uri: {type: String},
        scryfall_uri: {type: String},
        layout: {type: String},
        highres_image: {type: Boolean},
        image_status: {type: String},
        image_uris: {type: Object},
        mana_cost: {type: String},
        cmc: {type: Number},
        type_line: {type: String},
        oracle_text: {type: String},
        power: {type: String},
        toughness: {type: String},
        colors: [{type: String}],
        color_identity: [{type: String}],
        keywords: [{type: String}],
        legalities: {type: Object},
        games: [{type: String}],
        reserved: {type: Boolean},
        foil: {type: Boolean},
        nonfoil: {type: Boolean},
        finishes: [{type: String}],
        oversized: {type: Boolean},
        promo: {type: Boolean},
        reprint: {type: Boolean},
        variation: {type: Boolean},
        set_id: {type: String},
        set: {type: String},
        set_name: {type: String},
        set_type: {type: String},
        set_uri: {type: String},
        set_search_uri: {type: String},
        scryfall_set_uri: {type: String},
        rulings_uri: {type: String},
        prints_search_uri: {type: String},
        collector_number: {type: String},
        digital: {type: Boolean},
        rarity: {type: String},
        flavor_text: {type: String},
        card_back_id: {type: String},
        artist: {type: String},
        artist_ids: [{type: String}],
        illustration_id: {type: String},
        border_color: {type: String},
        frame: {type: String},
        full_art: {type: Boolean},
        textless: {type: Boolean},
        booster: {type: Boolean},
        story_spotlight: {type: Boolean},
        edhrec_rank: {type: Number},
        penny_rank: {type: Number},
        prices: {type: Object},
        related_uris: {type: Object},
	},
);

export type MtgCardDocument = HydratedDocument<IMtgCard>;

export const MtgCardModel = model('MtgCard', schema);